name: vehicle-classification
channels:
  - defaults
dependencies:
  - certifi=2019.9.11=py36_0
  - pip=19.2.3=py36_0
  - python=3.6.9=h5500b2f_0
  - setuptools=41.2.0=py36_0
  - sqlite=3.29.0=he774522_0
  - vc=14.1=h0510ff6_4
  - vs2015_runtime=14.16.27012=hf0eaf9b_0
  - wheel=0.33.6=py36_0
  - wincertstore=0.2=py36h7fe50ca_0
  - pip:
    - attrs==19.1.0
    - backcall==0.1.0
    - bleach==3.1.0
    - colorama==0.4.1
    - cycler==0.10.0
    - decorator==4.4.0
    - defusedxml==0.6.0
    - entrypoints==0.3
    - ipykernel==5.1.2
    - ipython==7.8.0
    - ipython-genutils==0.2.0
    - jedi==0.15.1
    - jinja2==2.10.1
    - joblib==0.13.2
    - jsonschema==3.0.2
    - jupyter-client==5.3.3
    - jupyter-core==4.5.0
    - kiwisolver==1.1.0
    - markupsafe==1.1.1
    - matplotlib==3.1.1
    - mistune==0.8.4
    - nbconvert==5.6.0
    - nbformat==4.4.0
    - notebook==6.0.1
    - numpy==1.17.2
    - opencv-python==4.1.1.26
    - pandas==0.25.1
    - pandocfilters==1.4.2
    - parso==0.5.1
    - pickleshare==0.7.5
    - pillow==6.1.0
    - prometheus-client==0.7.1
    - prompt-toolkit==2.0.9
    - pygments==2.4.2
    - pyparsing==2.4.2
    - pyrsistent==0.15.4
    - python-dateutil==2.8.0
    - pytz==2019.2
    - pywin32==225
    - pywinpty==0.5.5
    - pyzmq==18.1.0
    - scikit-learn==0.21.3
    - scipy==1.3.1
    - seaborn==0.9.0
    - send2trash==1.5.0
    - six==1.12.0
    - sklearn==0.0
    - terminado==0.8.2
    - testpath==0.4.2
    - torch==1.2.0
    - torchvision==0.4.0
    - tornado==6.0.3
    - traitlets==4.3.2
    - wcwidth==0.1.7
    - webencodings==0.5.1
prefix: C:\Anaconda3\envs\vehicle-classification

